python ../src_bio/train_bio.py --data_dir ../dataset/chr \
--transformer_type bert \
--model_name_or_path allenai/scibert_scivocab_cased \
--train_file train.data \
--dev_file dev.data \
--test_file test.data \
--train_batch_size 4 \
--test_batch_size 4 \
--num_labels 1 \
--learning_rate 2e-5 \
--max_grad_norm 1.0 \
--warmup_ratio 0.06 \
--num_train_epochs 30.0 \
--seed 66 \
--num_class 2
